In [11]:
from advectionGP import Model, FixedSensorModel, EQ
import numpy as np

X = np.array([[0,10,3,4],[0,2,6,7],[0,1,3,7],[0,1,6,4],[2,4,3,4],[2,4,6,7],[2,3,3,7],[2,3,6,4]])
y = np.array([12,13,15,16,13,14,10,9])
boundary = ([0,0,0],[10,10,10])

k = EQ(1.0, 2.0)

sensors = FixedSensorModel(X,5)
m = Model(resolution=[4,4,4],boundary=boundary,N_feat=15,noise_std=5.0,kernel=k,sensormodel=sensors)

In [12]:
for h in sensors.getHs(m):
    print(h)

-1 5 0 2 1 1
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
-1 1 1 3 2 2
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
-1 1 0 2 2 2
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
-1 1 1 3 1 1
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0.

In [4]:
m.getGridCoord(np.array([[9,9,9],[5,0,0]]))

array([[10, 10, 10],
       [ 6,  0,  0]])

In [7]:
X[4:4,:]

array([], shape=(0, 4), dtype=int64)

In [6]:
X[:,[0,2,3]]

array([[0, 3, 4],
       [0, 6, 7],
       [0, 3, 7],
       [0, 6, 4],
       [2, 3, 4],
       [2, 6, 7],
       [2, 3, 7],
       [2, 6, 4]])

In [1]:
for h in sensors.getHs():
    print(h)

NameError: name 'sensors' is not defined

In [2]:
tloc = np.linspace(boundary[0][2],boundary[1][2],16)
xloc=np.linspace(0.5,7.5,5)
yloc=np.linspace(0.5,7.5,5)
sensN = len(xloc)*len(yloc)
obsN = len(tloc)
coords = np.asarray(np.meshgrid(xloc,yloc)).reshape(2,sensN)

In [3]:
coords.shape

(2, 25)